### ISSUE TITLE
On second run db.Fold function causes a segmentation violation

### ISSUE THREAD

**Issue by Lexicon9** [Johnnydouble/FileMango#8]
works fine on first run, after a second run without deleting the 000000000.data file gives this error:
```
loading config... done
loading database... done
watching...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x51c102]

goroutine 1 [running]:
github.com/prologic/bitcask.(*Bitcask).Fold(0x0, 0x617938, 0xc000000180, 0x5a85f5)
        /home/melkor/go/pkg/mod/github.com/prologic/bitcask@v0.3.10/bitcask.go:304 +0x62
FileMango/src/db.FoldQueue(...)
        /home/melkor/go/src/FileMango/src/db/database.go:19
FileMango/src/scheduler.addInitialJobs()
        /home/melkor/go/src/FileMango/src/scheduler/worker_pool.go:147 +0x39
FileMango/src/scheduler.RunAnalysis()
        /home/melkor/go/src/FileMango/src/scheduler/worker_pool.go:28 +0x3a
main.run()
        /home/melkor/go/src/FileMango/main.go:37 +0x356
main.main()
        /home/melkor/go/src/FileMango/main.go:17 +0x25

Process finished with exit code 2
```
if the 000000000.data file is deleted works fine again.

**Comment by Johnnydouble** [comment]
I am having issues replicating this.

**Comment by Johnnydouble** [comment]
I managed to replicate this in a new virtual machine. The issue seems to be with getting a valid pointer to the database after the initial run.

**Comment by Johnnydouble** [comment]
This seems to be an issue with calling any function on the database pointer after getting it for the second time. It does not appear to be specific to db.Fold().
